import type { Category, Mode } from "../../src/types";
import type { FetchStrategy } from "./fetchers";

export interface Venue {
  name: string;
  url: string;
  /** Published iCal feed — extracted deterministically, before HTML/LLM. */
  icsUrl?: string;
  category: Category;
  defaultMode: Mode;
  whereTemplate: string;
  fetch?: FetchStrategy;
  altSources?: { url: string; fetch?: FetchStrategy }[];
  notes?: string;
}

// Only venues that returned usable HTML during past sweeps.
// Ones that 403/widget-render are excluded.
export const VENUES: Venue[] = [
  {
    name: "Interference Archive",
    url: "https://interferencearchive.org/events/",
    category: "community",
    defaultMode: "make",
    whereTemplate: "314 7th St, Park Slope",
  },
  {
    // Lincoln Center's big free summer festival — concerts, dance parties,
    // silent discos, social dancing. JS-rendered, so playwright + LLM.
    name: "Summer for the City",
    url: "https://lincolncenter.org/series/summer-for-the-city",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Lincoln Center (Summer for the City)",
    fetch: "playwright",
  },
  {
    name: "The Tank",
    url: "https://thetanknyc.org/tankcalendar",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Tank, 312 W 36th St, Midtown West",
  },
  {
    name: "Brooklyn Art Haus",
    url: "https://www.bkarthaus.com/shows-events",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Brooklyn Art Haus, 25 Marcy Ave, Williamsburg",
  },
  {
    name: "New York Live Arts",
    url: "https://newyorklivearts.org/calendar/",
    category: "dance",
    defaultMode: "witness",
    whereTemplate: "New York Live Arts, 219 W 19th St, Chelsea",
  },
  {
    name: "Abrons Arts Center",
    url: "https://www.abronsartscenter.org/performing-arts",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Abrons Arts Center, 466 Grand St, LES",
  },
  {
    name: "Baryshnikov Arts Center",
    url: "https://baryshnikovarts.org/",
    category: "dance",
    defaultMode: "witness",
    whereTemplate: "Baryshnikov Arts Center, 450 W 37th St",
    fetch: "playwright",
  },
  {
    name: "Symphony Space",
    url: "https://www.symphonyspace.org/",
    category: "literature",
    defaultMode: "witness",
    whereTemplate: "Symphony Space, Upper West Side",
  },
  {
    name: "Film Forum",
    url: "https://www.filmforum.org/now-playing",
    category: "film",
    defaultMode: "witness",
    whereTemplate: "Film Forum, 209 W Houston St",
  },
  {
    name: "Wendy's Subway",
    url: "https://www.wendyssubway.com/programs",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "Wendy's Subway, Bushwick/Ridgewood border",
  },
  {
    name: "UnionDocs",
    url: "https://uniondocs.org/events/category/workshops/list/",
    icsUrl: "https://uniondocs.org/events/?ical=1",
    category: "film",
    defaultMode: "make",
    whereTemplate: "UnionDocs, Ridgewood",
  },
  {
    name: "Mono No Aware",
    url: "http://mononoawarefilm.com/community-workshops",
    category: "film",
    defaultMode: "make",
    whereTemplate: "Downtown Brooklyn",
  },
  {
    name: "Bushwick Community Darkroom",
    url: "https://www.bushwickcommunitydarkroom.com/events",
    category: "making",
    defaultMode: "make",
    whereTemplate: "334 Himrod St, Bushwick",
  },
  {
    name: "ISSUE Project Room",
    url: "https://issueprojectroom.org/calendar",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "ISSUE Project Room, 22 Boerum Pl, Downtown Brooklyn",
  },
  {
    name: "Roulette",
    url: "https://roulette.org/calendar",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Roulette, 509 Atlantic Ave, Brooklyn",
  },
  {
    name: "New York Theatre Workshop",
    url: "https://www.nytw.org/2026-27-season/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "New York Theatre Workshop, 79 E 4th St",
  },
  {
    name: "CATCH!",
    url: "https://catchseries.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Rotating Brooklyn venues — check catchseries.org",
  },
  {
    name: "Wavefield",
    url: "https://wavefield.media/events",
    category: "tech",
    defaultMode: "witness",
    whereTemplate: "Wavefield, Brooklyn",
  },
  {
    name: "DADA",
    url: "https://dadabar.nyc/program",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "DADA, 6047 Myrtle Ave, Ridgewood",
  },
  {
    name: "SUPR OMEN",
    url: "https://supromen.com/events/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "SUPR OMEN, 1 Knickerbocker Ave, Brooklyn",
  },
  {
    name: "The Arts Center at Governors Island",
    url: "https://lmcc.net/lmcc-arts-center-at-governors-island/",
    icsUrl: "https://lmcc.net/events/?ical=1",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Arts Center at Governors Island (LMCC), Building 110",
  },
  {
    name: "Francis Kite Club",
    url: "https://www.franciskiteclub.com/",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Francis Kite Club, 40 Loisaida Ave (Ave C), LES",
  },
  {
    name: "Telepathy",
    url: "https://pools.events/o/telepathy/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Telepathy · Brooklyn",
  },
  {
    name: "Performance Space New York",
    url: "https://performancespacenewyork.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Performance Space New York, 150 First Ave, East Village",
  },
  {
    name: "Chez Bushwick",
    url: "https://www.chezbushwick.net/",
    category: "dance",
    defaultMode: "make",
    whereTemplate: "Chez Bushwick, Brooklyn",
  },
  {
    name: "Footlight Presents (Windjammer)",
    url: "https://www.footlightunderground.com/",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "The Windjammer, 552 Grandview Ave, Ridgewood",
  },
  {
    name: "Delight Factory",
    url: "https://www.delightfactorynyc.com/events",
    category: "community",
    defaultMode: "witness",
    whereTemplate: "Delight Factory, 303 Saratoga Ave, Ocean Hill",
  },
  {
    name: "Museum of Reclaimed Urban Space (MoRUS)",
    url: "https://www.morusnyc.org/",
    category: "community",
    defaultMode: "witness",
    whereTemplate: "MoRUS, 155 Ave C, LES",
  },
  {
    name: "Recess",
    url: "https://www.recessart.org/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Recess, Clinton Hill",
  },
  {
    name: "Sleepwalk",
    url: "https://sleepwalk.nyc/events",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Sleepwalk, 251 Bushwick Ave, East Williamsburg",
  },
  {
    name: "e-flux",
    url: "https://www.e-flux.com/live/",
    category: "making",
    defaultMode: "witness",
    whereTemplate: "e-flux, 172 Classon Ave, Brooklyn",
    fetch: "playwright",
  },
  {
    name: "Cybernetics Library",
    url: "https://luma.com/cyberneticslibrary",
    category: "literature",
    defaultMode: "witness",
    whereTemplate: "Cybernetics Library at Prime Produce, 424 W 54th St",
  },
  {
    name: "Prime Produce",
    url: "https://www.primeproduce.coop/",
    category: "community",
    defaultMode: "witness",
    whereTemplate: "Prime Produce, 424 W 54th St, Hell's Kitchen",
  },
  {
    name: "FourOneOne",
    url: "https://www.fouroneoneprojects.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "FourOneOne, 411 Kent Ave, Williamsburg",
  },

  // ── Previously blocked / widget-hidden calendars — unblocked via headless
  // Chromium (Playwright). Adds ~1min of workflow time.
  {
    name: "La MaMa",
    url: "https://www.lamama.org/whats-on",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "La MaMa, 66 E 4th St, East Village",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/la-mama-etc" }],
  },
  {
    name: "The Public Theater",
    url: "https://publictheater.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Public Theater, 425 Lafayette, Manhattan",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/the-public-theater" }],
  },
  {
    name: "Joe's Pub",
    url: "https://publictheater.org/joes-pub/",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Joe's Pub, 425 Lafayette, Manhattan",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/joe-s-pub" }],
  },
  {
    name: "St. Ann's Warehouse",
    url: "https://stannswarehouse.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "St. Ann's Warehouse, DUMBO",
    fetch: "playwright",
  },
  {
    name: "National Sawdust",
    url: "https://nationalsawdust.org/calendar",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "National Sawdust, 80 N 6th St, Williamsburg",
    fetch: "playwright",
    altSources: [
      { url: "https://donyc.com/venues/national-sawdust" },
    ],
  },
  {
    name: "Ars Nova",
    url: "https://arsnovanyc.com/whats-on/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Ars Nova, 511 W 54th St, Hell's Kitchen",
    fetch: "playwright",
  },
  {
    name: "Metrograph",
    url: "https://metrograph.com/",
    category: "film",
    defaultMode: "witness",
    whereTemplate: "Metrograph, 7 Ludlow St, LES",
    fetch: "playwright",
  },
  {
    name: "Film at Lincoln Center",
    url: "https://www.filmlinc.org/calendar/",
    category: "film",
    defaultMode: "witness",
    whereTemplate: "Film at Lincoln Center, Walter Reade + EBM · Lincoln Center",
    fetch: "playwright",
  },
  {
    name: "Mercury Store",
    url: "https://www.mercurystore.com/programs",
    category: "theatre",
    defaultMode: "make",
    whereTemplate: "Mercury Store, Gowanus",
    fetch: "playwright",
  },
  {
    name: "Nuyorican Poets Cafe",
    url: "https://www.nuyorican.org/events",
    category: "literature",
    defaultMode: "witness",
    whereTemplate: "Nuyorican Poets Cafe, 236 E 3rd St, LES",
    fetch: "playwright",
  },
  {
    name: "FRIGID NY (Under St. Marks)",
    url: "https://frigid.nyc/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "FRIGID NY (Under St. Marks), 94 St. Marks Pl, East Village",
    fetch: "playwright",
  },
  {
    name: "BAM",
    url: "https://www.bam.org/whats-on",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "BAM, 30 Lafayette Ave, Fort Greene",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/bam-brooklyn-academy-of-music" }],
  },
  {
    name: "The Bushwick Starr",
    url: "https://www.thebushwickstarr.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Bushwick Starr, Eldert Street, Bushwick",
    fetch: "playwright",
  },
  {
    name: "Target Margin Theater",
    url: "https://www.targetmargin.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Target Margin, Doxsee Theater, Sunset Park",
    fetch: "playwright",
  },
  {
    name: "Soho Playhouse",
    url: "https://sohoplayhouse.com/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Soho Playhouse, 15 Vandam St, Hudson Square",
    fetch: "playwright",
  },
  {
    name: "Atlantic Theater Company",
    url: "https://atlantictheater.org/whats-on/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Atlantic Theater Company, 336 W 20th St, Chelsea",
    fetch: "playwright",
  },
  {
    name: "Bedlam",
    url: "https://www.bedlam.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Bedlam (rotating venues)",
    fetch: "playwright",
  },

  // ── Making / creative-practice venues ───────────────────────────────
  // Class- and workshop-forward spaces. Most are JS-rendered (Squarespace/
  // Wix), so they use playwright + fall through to LLM extraction.
  {
    name: "Textile Arts Center",
    url: "https://textileartscenter.com/adult-classes/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Textile Arts Center, 505 Carroll St, Gowanus",
    fetch: "playwright",
  },
  {
    name: "Gowanus Print Lab",
    url: "https://www.gowanusprintlab.com/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Gowanus Print Lab, 232 3rd St, Gowanus",
    fetch: "playwright",
  },
  {
    name: "Center for Book Arts",
    url: "https://centerforbookarts.org/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Center for Book Arts, 28 W 27th St, 3rd Fl, Flatiron",
    fetch: "playwright",
  },
  {
    name: "Penumbra Foundation",
    url: "https://www.penumbrafoundation.org/workshops",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Penumbra Foundation, 36 E 30th St, Kips Bay",
    fetch: "playwright",
  },
  {
    name: "BKLYN CLAY",
    url: "https://www.bklynclay.com/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "BKLYN CLAY, 63 Flushing Ave, Bldg 280, Navy Yard",
    fetch: "playwright",
  },
  {
    name: "Greenwich House Pottery",
    url: "https://greenwichhouse.org/pottery/classes/",
    category: "making",
    // This feed is the Jane Hartsook Gallery's, not the pottery school's
    // class list — everything on it is an exhibition or an artist talk.
    defaultMode: "witness",
    whereTemplate: "Greenwich House Pottery, 16 Jones St, West Village",
    fetch: "playwright",
  },
  {
    name: "Brooklyn Glass",
    url: "https://www.brooklynglass.com/classes/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Brooklyn Glass, 142 13th St, Gowanus",
    fetch: "playwright",
  },
  {
    name: "Brooklyn Craft Company",
    url: "https://www.brooklyncraftcompany.com/collections/all-workshops",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Brooklyn Craft Company, 165 Greenpoint Ave, Greenpoint",
    fetch: "playwright",
  },
  {
    name: "Makerspace NYC",
    url: "https://www.makerspace.nyc/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Makerspace NYC, 41-28 39th St, Sunnyside",
    fetch: "playwright",
  },
  {
    name: "NYC Resistor",
    url: "https://www.nycresistor.com/classes/",
    category: "tech",
    defaultMode: "make",
    whereTemplate: "NYC Resistor, 87 3rd Ave, 4th Fl, Boerum Hill",
    fetch: "playwright",
  },
  {
    name: "Genspace",
    url: "https://www.genspace.org/classes",
    category: "tech",
    defaultMode: "make",
    whereTemplate: "Genspace, 132 32nd St, Bldg 6, Sunset Park",
    fetch: "playwright",
  },
  {
    name: "Powrplnt",
    url: "https://powrplnt.org/",
    category: "tech",
    defaultMode: "make",
    whereTemplate: "Powrplnt, 3 Willoughby Ave, Bushwick",
    fetch: "playwright",
  },
  {
    name: "Brooklyn Poets",
    url: "https://brooklynpoets.org/workshops/all",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "Brooklyn Poets (Brooklyn / online)",
    fetch: "playwright",
  },
  {
    name: "Flux Factory",
    url: "https://www.fluxfactory.org/events/",
    category: "community",
    defaultMode: "make",
    whereTemplate: "Flux Factory, 39-31 29th St, Long Island City",
    fetch: "playwright",
  },

  // ── Making, wave 2 (verified July 2026) ─────────────────────────────
  // Static-first (default): detail-crawl / platform / LLM handle these.
  // Flip individual venues to playwright if a scan shows them returning 0.
  {
    name: "UrbanGlass",
    url: "https://urbanglass.org/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "UrbanGlass, 647 Fulton St, Fort Greene",
  },
  {
    name: "Lower East Side Printshop",
    url: "https://www.printshop.org/classes-workshops",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Lower East Side Printshop, 306 W 37th St, Garment District",
  },
  {
    name: "Robert Blackburn Printmaking Workshop",
    url: "https://www.rbpmw-efanyc.org/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "EFA Robert Blackburn Printmaking Workshop, 323 W 39th St",
  },
  {
    name: "Manhattan Graphics Center",
    url: "https://www.manhattangraphicscenter.org/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Manhattan Graphics Center, 250 W 40th St",
  },
  {
    name: "The Arm",
    url: "https://www.thearm.org/workshops",
    category: "making",
    defaultMode: "make",
    whereTemplate: "The Arm, 60 Broadway, Williamsburg",
  },
  {
    name: "Dieu Donné",
    url: "https://www.dieudonne.org/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Dieu Donné, Brooklyn Navy Yard",
  },
  {
    name: "Powerhouse Arts",
    url: "https://powerhousearts.org/fabrication/classes-workshops",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Powerhouse Arts, 322 3rd Ave, Gowanus",
  },
  {
    name: "Artshack Brooklyn",
    url: "https://www.artshackbrooklyn.org/studio/upcoming",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Artshack Brooklyn, 1345 Dean St, Bed-Stuy",
  },
  {
    name: "Choplet Ceramic Studio",
    url: "https://choplet.com/ceramic-classes/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Choplet, 238 Grand St, Williamsburg",
  },
  {
    name: "Gasworks NYC",
    url: "https://www.gasworksnyc.com/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Gasworks NYC, South Slope, Brooklyn",
  },
  {
    name: "BrickHouse Ceramic Art Center",
    url: "https://brickhouseny.com/pages/classes-overview",
    category: "making",
    defaultMode: "make",
    whereTemplate: "BrickHouse Ceramic Art Center, Long Island City",
  },
  {
    name: "Brooklyn Metal Works",
    url: "https://www.bkmetalworks.com/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Brooklyn Metal Works, 640 Dean St, Prospect Heights",
  },
  {
    name: "Craftsman Ave",
    url: "https://craftsmanave.com/workshops/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Craftsman Ave, Gowanus, Brooklyn",
  },
  {
    name: "Makeville Studio",
    url: "https://www.makeville.com/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Makeville Studio, Gowanus, Brooklyn",
  },
  {
    name: "Gowanus Darkroom",
    url: "https://www.gowanusdarkroom.com/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Gowanus Darkroom, Gowanus, Brooklyn",
  },
  {
    name: "International Center of Photography",
    url: "https://www.icp.org/school/courses-and-workshops",
    category: "making",
    defaultMode: "make",
    whereTemplate: "ICP, 84 Ludlow St, Lower East Side",
  },
  {
    name: "Loop of the Loom",
    url: "https://loopoftheloom.com/collections/weaving-classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Loop of the Loom, Upper East Side",
  },
  {
    name: "Art Students League of New York",
    url: "https://studioclasses.artstudentsleague.org/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Art Students League, 215 W 57th St, Midtown",
  },
  {
    name: "Materials for the Arts",
    url: "https://www.materialsforthearts.org/education/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Materials for the Arts, 33-00 Northern Blvd, Long Island City",
  },
  {
    name: "Millennium Film Workshop",
    url: "https://www.millenniumfilm.org/calendar",
    category: "film",
    defaultMode: "make",
    whereTemplate: "Millennium Film Workshop, Bushwick, Brooklyn",
  },
  {
    name: "DCTV",
    url: "https://www.dctvny.org/",
    category: "film",
    defaultMode: "make",
    whereTemplate: "DCTV, 87 Lafayette St, Chinatown",
  },
  {
    name: "School for Poetic Computation",
    url: "https://sfpc.study/",
    category: "tech",
    defaultMode: "make",
    whereTemplate: "School for Poetic Computation, Lower East Side",
  },
  {
    name: "Harvestworks",
    url: "https://www.harvestworks.org/",
    category: "sound",
    defaultMode: "make",
    whereTemplate: "Harvestworks, Governors Island / SoHo",
  },
  {
    name: "343 Labs",
    url: "https://www.343labs.com/nyc-courses-at-343-labs/",
    category: "sound",
    defaultMode: "make",
    whereTemplate: "343 Labs, 199 Lafayette St, SoHo",
  },
  {
    name: "Center for Fiction",
    url: "https://centerforfiction.org/writing-workshops/",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "Center for Fiction, 15 Lafayette Ave, Fort Greene",
  },
  {
    name: "Gotham Writers Workshop",
    url: "https://www.writingclasses.com/classes/nyc",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "Gotham Writers Workshop, 555 8th Ave, Midtown",
  },
  {
    name: "NY Writers Coalition",
    url: "https://nywriterscoalition.org/",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "NY Writers Coalition (workshops citywide)",
  },
  {
    name: "Bluestockings Cooperative",
    url: "https://bluestockings.com/events",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "Bluestockings, 116 Suffolk St, Lower East Side",
  },
  {
    name: "Jamaica Center for Arts and Learning",
    url: "https://jcal.org/classes",
    category: "community",
    defaultMode: "make",
    whereTemplate: "Jamaica Center for Arts and Learning, 161-04 Jamaica Ave, Queens",
  },

  // ── Making, wave 3 (verified July 2026, all-borough) ────────────────
  {
    name: "Pioneer Works",
    url: "https://pioneerworks.org/classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Pioneer Works, 159 Pioneer St, Red Hook",
  },
  {
    name: "Bushwick Print Lab",
    url: "https://bushwickprintlab.org/services/workshops/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Bushwick Print Lab, Bushwick, Brooklyn",
  },
  {
    name: "Works in Progress NYC",
    url: "https://www.worksinprogressnyc.org/silk-screen-classes/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Works in Progress NYC, East Village",
  },
  {
    name: "Manny Cantor Center",
    url: "https://mannycantor.org/art/art-classes/ceramics/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Manny Cantor Center, 197 East Broadway, Lower East Side",
  },
  {
    name: "Scratch Ceramics",
    url: "https://www.scratchceramics.com/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Scratch Ceramics, 658 Woodward Ave, Ridgewood",
  },
  {
    name: "Uptown Clay",
    url: "https://www.uptown-clay.com/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Uptown Clay, 4470 Broadway, Washington Heights",
  },
  {
    name: "AlterWork Studios",
    url: "https://www.alterworkstudios.com/purchase",
    category: "making",
    defaultMode: "make",
    whereTemplate: "AlterWork Studios, 40-20 22nd St, Long Island City",
  },
  {
    name: "Bronx River Art Center",
    url: "https://www.bronxriverart.org/education-adult-classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Bronx River Art Center, 1087 E Tremont Ave, West Farms, Bronx",
  },
  {
    name: "Fat Cat Fab Lab",
    url: "https://fatcatfablab.org/classes",
    category: "tech",
    defaultMode: "make",
    whereTemplate: "Fat Cat Fab Lab, 75 Christopher St, West Village",
  },
  {
    name: "Hack Manhattan",
    url: "https://hackmanhattan.com/events",
    category: "tech",
    defaultMode: "make",
    whereTemplate: "Hack Manhattan, 137 W 14th St, Manhattan",
  },
  {
    name: "Film-Makers' Cooperative",
    url: "https://film-makerscoop.com/screenings",
    category: "film",
    defaultMode: "make",
    whereTemplate: "Film-Makers' Cooperative, Gramercy, Manhattan",
  },
  {
    name: "Noguchi Museum",
    url: "https://www.noguchi.org/museum/calendar/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Noguchi Museum, 9-01 33rd Rd, Long Island City",
  },
  {
    name: "Socrates Sculpture Park",
    url: "https://socratessculpturepark.org/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Socrates Sculpture Park, 32-01 Vernon Blvd, Astoria",
  },
  {
    name: "Studio Museum in Harlem",
    url: "https://www.studiomuseum.org/exhibitions-and-events/workshops-courses",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Studio Museum in Harlem, 144 W 125th St, Harlem",
  },
  {
    name: "Word Up Community Bookshop",
    url: "https://wordupbooks.com/upcoming-events",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "Word Up Books, 2113 Amsterdam Ave, Washington Heights",
  },
  {
    name: "Building Beats",
    url: "https://buildingbeats.org/bbworkshops",
    category: "sound",
    defaultMode: "make",
    whereTemplate: "Building Beats (workshops citywide; HQ Greenpoint)",
  },
  {
    name: "Creative Music Studio",
    url: "https://creativemusic.org/workshops-2026/",
    category: "sound",
    defaultMode: "make",
    whereTemplate: "Creative Music Studio at Ibeam, 168 7th St, Gowanus",
  },
  {
    name: "BKC",
    url: "https://www.wearebkc.com/nyc-photography-classes",
    category: "making",
    defaultMode: "make",
    whereTemplate: "BKC, Bushwick, Brooklyn",
  },
  {
    name: "BRIC",
    url: "https://bricartsmedia.org/classes/",
    category: "tech",
    // Celebrate Brooklyn! is a concert series.
    defaultMode: "witness",
    whereTemplate: "BRIC, 647 Fulton St, Fort Greene",
    fetch: "playwright",
  },
  {
    name: "Museum of the Moving Image",
    url: "https://movingimage.org/education/",
    category: "film",
    defaultMode: "make",
    whereTemplate: "Museum of the Moving Image, 36-01 35th Ave, Astoria",
    fetch: "playwright",
  },
  {
    name: "El Museo del Barrio",
    url: "https://elmuseo.org/events/",
    category: "making",
    // An art museum: screenings, parties and book launches, with a
    // few family making programs. Those carry their own signals.
    defaultMode: "witness",
    whereTemplate: "El Museo del Barrio, 1230 Fifth Ave, East Harlem",
    fetch: "playwright",
  },
  // Added from H.R.L.'s verified making-venue list (2026-07). Both scrape
  // statically via Squarespace event collections — no playwright needed —
  // confirmed by scripts/probe-venues.ts.
  {
    name: "Brooklyn Shoe Space",
    url: "https://brooklynshoespace.com/schedule",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Brooklyn Shoe Space, 87 Richardson St, East Williamsburg",
    fetch: "static",
  },
  {
    name: "Mostly Good Studios",
    url: "https://mostlygoodstudios.com/calendar",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Mostly Good Studios, Astoria",
    fetch: "static",
  },
  // A bar arcade: mostly gigs and DJ nights (hence witness-default), but it
  // hosts genuine participatory making — WordHack, playtests, game jams — which
  // flip to make on their title signals and land in Practice. The witness cap
  // keeps its nightlife from flooding the calendar.
  {
    name: "Wonderville",
    url: "https://wonderville.nyc/events",
    category: "tech",
    defaultMode: "witness",
    whereTemplate: "Wonderville, 1186 Broadway, Bushwick",
    fetch: "static",
  },
];
