import type { Category, Mode } from "../../src/types";
import type { FetchStrategy } from "./fetchers";

export interface Venue {
  name: string;
  url: string;
  /** Published iCal feed — extracted deterministically, before HTML/LLM. */
  icsUrl?: string;
  category: Category;
  defaultMode: Mode;
  whereTemplate: string;
  fetch?: FetchStrategy;
  altSources?: { url: string; fetch?: FetchStrategy }[];
  notes?: string;
}

// Only venues that returned usable HTML during past sweeps.
// Ones that 403/widget-render are excluded.
export const VENUES: Venue[] = [
  {
    name: "Interference Archive",
    url: "https://interferencearchive.org/events/",
    category: "community",
    defaultMode: "make",
    whereTemplate: "314 7th St, Park Slope",
  },
  {
    name: "The Tank",
    url: "https://thetanknyc.org/tankcalendar",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Tank, 312 W 36th St, Midtown West",
  },
  {
    name: "Brooklyn Art Haus",
    url: "https://www.bkarthaus.com/shows-events",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Brooklyn Art Haus, 25 Marcy Ave, Williamsburg",
  },
  {
    name: "New York Live Arts",
    url: "https://newyorklivearts.org/calendar/",
    category: "dance",
    defaultMode: "witness",
    whereTemplate: "New York Live Arts, 219 W 19th St, Chelsea",
  },
  {
    name: "Abrons Arts Center",
    url: "https://www.abronsartscenter.org/performing-arts",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Abrons Arts Center, 466 Grand St, LES",
  },
  {
    name: "Baryshnikov Arts Center",
    url: "https://baryshnikovarts.org/",
    category: "dance",
    defaultMode: "witness",
    whereTemplate: "Baryshnikov Arts Center, 450 W 37th St",
    fetch: "playwright",
  },
  {
    name: "Symphony Space",
    url: "https://www.symphonyspace.org/",
    category: "literature",
    defaultMode: "witness",
    whereTemplate: "Symphony Space, Upper West Side",
  },
  {
    name: "Film Forum",
    url: "https://www.filmforum.org/now-playing",
    category: "film",
    defaultMode: "witness",
    whereTemplate: "Film Forum, 209 W Houston St",
  },
  {
    name: "Wendy's Subway",
    url: "https://www.wendyssubway.com/programs",
    category: "literature",
    defaultMode: "make",
    whereTemplate: "Wendy's Subway, Bushwick/Ridgewood border",
  },
  {
    name: "UnionDocs",
    url: "https://uniondocs.org/events/category/workshops/list/",
    icsUrl: "https://uniondocs.org/events/?ical=1",
    category: "film",
    defaultMode: "make",
    whereTemplate: "UnionDocs, Ridgewood",
  },
  {
    name: "Mono No Aware",
    url: "http://mononoawarefilm.com/community-workshops",
    category: "film",
    defaultMode: "make",
    whereTemplate: "Downtown Brooklyn",
  },
  {
    name: "Bushwick Community Darkroom",
    url: "https://www.bushwickcommunitydarkroom.com/events",
    category: "making",
    defaultMode: "make",
    whereTemplate: "334 Himrod St, Bushwick",
  },
  {
    name: "ISSUE Project Room",
    url: "https://issueprojectroom.org/calendar",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "ISSUE Project Room, 22 Boerum Pl, Downtown Brooklyn",
  },
  {
    name: "Roulette",
    url: "https://roulette.org/calendar",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Roulette, 509 Atlantic Ave, Brooklyn",
  },
  {
    name: "New York Theatre Workshop",
    url: "https://www.nytw.org/2026-27-season/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "New York Theatre Workshop, 79 E 4th St",
  },
  {
    name: "CATCH!",
    url: "https://catchseries.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Rotating Brooklyn venues — check catchseries.org",
  },
  {
    name: "Wavefield",
    url: "https://wavefield.media/events",
    category: "tech",
    defaultMode: "witness",
    whereTemplate: "Wavefield, Brooklyn",
  },
  {
    name: "DADA",
    url: "https://dadabar.nyc/program",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "DADA, 6047 Myrtle Ave, Ridgewood",
  },
  {
    name: "SUPR OMEN",
    url: "https://supromen.com/events/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "SUPR OMEN, 1 Knickerbocker Ave, Brooklyn",
  },
  {
    name: "The Arts Center at Governors Island",
    url: "https://lmcc.net/lmcc-arts-center-at-governors-island/",
    icsUrl: "https://lmcc.net/events/?ical=1",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Arts Center at Governors Island (LMCC), Building 110",
  },
  {
    name: "Francis Kite Club",
    url: "https://www.franciskiteclub.com/",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Francis Kite Club, 40 Loisaida Ave (Ave C), LES",
  },
  {
    name: "Telepathy",
    url: "https://pools.events/o/telepathy/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Telepathy · Brooklyn",
  },
  {
    name: "Performance Space New York",
    url: "https://performancespacenewyork.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Performance Space New York, 150 First Ave, East Village",
  },
  {
    name: "Chez Bushwick",
    url: "https://www.chezbushwick.net/",
    category: "dance",
    defaultMode: "make",
    whereTemplate: "Chez Bushwick, Brooklyn",
  },
  {
    name: "Footlight Presents (Windjammer)",
    url: "https://www.footlightunderground.com/",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "The Windjammer, 552 Grandview Ave, Ridgewood",
  },
  {
    name: "Delight Factory",
    url: "https://www.delightfactorynyc.com/events",
    category: "community",
    defaultMode: "witness",
    whereTemplate: "Delight Factory, 303 Saratoga Ave, Ocean Hill",
  },
  {
    name: "Museum of Reclaimed Urban Space (MoRUS)",
    url: "https://www.morusnyc.org/",
    category: "community",
    defaultMode: "witness",
    whereTemplate: "MoRUS, 155 Ave C, LES",
  },
  {
    name: "Recess",
    url: "https://www.recessart.org/",
    category: "making",
    defaultMode: "make",
    whereTemplate: "Recess, Clinton Hill",
  },
  {
    name: "Sleepwalk",
    url: "https://sleepwalk.nyc/events",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Sleepwalk, 251 Bushwick Ave, East Williamsburg",
  },
  {
    name: "e-flux",
    url: "https://www.e-flux.com/live/",
    category: "making",
    defaultMode: "witness",
    whereTemplate: "e-flux, 172 Classon Ave, Brooklyn",
    fetch: "playwright",
  },
  {
    name: "Cybernetics Library",
    url: "https://luma.com/cyberneticslibrary",
    category: "literature",
    defaultMode: "witness",
    whereTemplate: "Cybernetics Library at Prime Produce, 424 W 54th St",
  },
  {
    name: "Prime Produce",
    url: "https://www.primeproduce.coop/",
    category: "community",
    defaultMode: "witness",
    whereTemplate: "Prime Produce, 424 W 54th St, Hell's Kitchen",
  },
  {
    name: "FourOneOne",
    url: "https://www.fouroneoneprojects.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "FourOneOne, 411 Kent Ave, Williamsburg",
  },

  // ── Previously blocked / widget-hidden calendars — unblocked via headless
  // Chromium (Playwright). Adds ~1min of workflow time.
  {
    name: "La MaMa",
    url: "https://www.lamama.org/whats-on",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "La MaMa, 66 E 4th St, East Village",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/la-mama-etc" }],
  },
  {
    name: "The Public Theater",
    url: "https://publictheater.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Public Theater, 425 Lafayette, Manhattan",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/the-public-theater" }],
  },
  {
    name: "Joe's Pub",
    url: "https://publictheater.org/joes-pub/",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "Joe's Pub, 425 Lafayette, Manhattan",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/joe-s-pub" }],
  },
  {
    name: "St. Ann's Warehouse",
    url: "https://stannswarehouse.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "St. Ann's Warehouse, DUMBO",
    fetch: "playwright",
  },
  {
    name: "National Sawdust",
    url: "https://nationalsawdust.org/calendar",
    category: "sound",
    defaultMode: "witness",
    whereTemplate: "National Sawdust, 80 N 6th St, Williamsburg",
    fetch: "playwright",
    altSources: [
      { url: "https://donyc.com/venues/national-sawdust" },
    ],
  },
  {
    name: "Ars Nova",
    url: "https://arsnovanyc.com/whats-on/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Ars Nova, 511 W 54th St, Hell's Kitchen",
    fetch: "playwright",
  },
  {
    name: "Metrograph",
    url: "https://metrograph.com/",
    category: "film",
    defaultMode: "witness",
    whereTemplate: "Metrograph, 7 Ludlow St, LES",
    fetch: "playwright",
  },
  {
    name: "Film at Lincoln Center",
    url: "https://www.filmlinc.org/calendar/",
    category: "film",
    defaultMode: "witness",
    whereTemplate: "Film at Lincoln Center, Walter Reade + EBM · Lincoln Center",
    fetch: "playwright",
  },
  {
    name: "Mercury Store",
    url: "https://www.mercurystore.com/programs",
    category: "theatre",
    defaultMode: "make",
    whereTemplate: "Mercury Store, Gowanus",
    fetch: "playwright",
  },
  {
    name: "Nuyorican Poets Cafe",
    url: "https://www.nuyorican.org/events",
    category: "literature",
    defaultMode: "witness",
    whereTemplate: "Nuyorican Poets Cafe, 236 E 3rd St, LES",
    fetch: "playwright",
  },
  {
    name: "FRIGID NY (Under St. Marks)",
    url: "https://frigid.nyc/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "FRIGID NY (Under St. Marks), 94 St. Marks Pl, East Village",
    fetch: "playwright",
  },
  {
    name: "BAM",
    url: "https://www.bam.org/whats-on",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "BAM, 30 Lafayette Ave, Fort Greene",
    fetch: "playwright",
    altSources: [{ url: "https://donyc.com/venues/bam-brooklyn-academy-of-music" }],
  },
  {
    name: "The Bushwick Starr",
    url: "https://www.thebushwickstarr.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "The Bushwick Starr, Eldert Street, Bushwick",
    fetch: "playwright",
  },
  {
    name: "Target Margin Theater",
    url: "https://www.targetmargin.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Target Margin, Doxsee Theater, Sunset Park",
    fetch: "playwright",
  },
  {
    name: "Soho Playhouse",
    url: "https://sohoplayhouse.com/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Soho Playhouse, 15 Vandam St, Hudson Square",
    fetch: "playwright",
  },
  {
    name: "Atlantic Theater Company",
    url: "https://atlantictheater.org/whats-on/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Atlantic Theater Company, 336 W 20th St, Chelsea",
    fetch: "playwright",
  },
  {
    name: "Bedlam",
    url: "https://www.bedlam.org/",
    category: "theatre",
    defaultMode: "witness",
    whereTemplate: "Bedlam (rotating venues)",
    fetch: "playwright",
  },
];
